-- 4. 해외영업팀 직원 조회
SELECT
    E.EMP_NAME,
    J.JOB_NAME,
    E.DEPT_CODE,
    D.DEPT_TITLE
FROM EMPLOYEE E
         JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
         JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE D.DEPT_TITLE LIKE '해외영업%';