SELECT E.EMP_NAME, E.EMP_NO, D.DEPT_TITLE, J.JOB_NAME
FROM EMPLOYEE E
         JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
         JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE SUBSTR(E.EMP_NO, 1, 2) BETWEEN '70' AND '79'
  AND SUBSTR(E.EMP_NO, 8, 1) LIKE '2%'
  AND E.EMP_NAME LIKE '전%';
