-- 7. 한국과 일본에 근무하는 직원 조회
SELECT
    E.EMP_NAME,
    D.DEPT_TITLE,
    L.LOCAL_NAME,
    N.NATIONAL_NAME
FROM EMPLOYEE E
         JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
         JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
         JOIN NATION N ON L.NATIONAL_CODE = N.NATIONAL_CODE
WHERE N.NATIONAL_CODE IN ('KO', 'JP');