SELECT D.DEPT_TITLE AS '부서명', SUM(E.SALARY) AS 부서별급여합계
FROM EMPLOYEE E
         JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
GROUP BY DEPT_CODE
HAVING SUM(E.SALARY) > (SELECT SUM(SALARY) * 0.2
                        FROM EMPLOYEE);