SELECT DISTINCT e.EMP_ID AS '사번', e.EMP_NAME AS '이름', d.DEPT_TITLE AS '부서명', j.JOB_NAME AS '직급', '관리자' AS 구분
FROM EMPLOYEE e
         LEFT JOIN DEPARTMENT d ON e.DEPT_CODE = d.DEPT_ID
         LEFT JOIN JOB j ON e.JOB_CODE = j.JOB_CODE
WHERE EMP_ID IN (SELECT MANAGER_ID
                 FROM EMPLOYEE
                 WHERE MANAGER_ID IS NOT NULL)

UNION

SELECT e.EMP_ID AS '사번', e.EMP_NAME AS '이름', d.DEPT_TITLE AS '부서명', j.JOB_NAME AS '직급', '직원' AS 구분
FROM EMPLOYEE e
         LEFT JOIN DEPARTMENT d ON e.DEPT_CODE = d.DEPT_ID
         LEFT JOIN JOB j ON e.JOB_CODE = j.JOB_CODE
WHERE EMP_ID NOT IN (SELECT MANAGER_ID
                     FROM EMPLOYEE
                     WHERE MANAGER_ID IS NOT NULL)

ORDER BY 구분, 1;