SELECT
    D.DEPT_TITLE,
    SUM(E.SALARY) AS ACTUAL_DEPT_SAL_SUM,
    SUM(SG.MAX_SAL) AS DEPT_SAL_LIMIT_SUM
FROM EMPLOYEE E
         JOIN DEPARTMENT D
              ON E.DEPT_CODE = D.DEPT_ID
         JOIN SAL_GRADE SG
              ON E.SAL_LEVEL = SG.SAL_LEVEL
GROUP BY D.DEPT_TITLE
HAVING SUM(E.SALARY) > (
    SELECT 0.2 * SUM(SG2.MAX_SAL)
    FROM EMPLOYEE E2
             JOIN SAL_GRADE SG2
                  ON E2.SAL_LEVEL = SG2.SAL_LEVEL
);
