-- 6. 부서코드 D2인 직원 조회
SELECT
    E.EMP_NAME,
    J.JOB_NAME,
    D.DEPT_TITLE,
    L.LOCAL_NAME
FROM EMPLOYEE E
         JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
         JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
         JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
WHERE E.DEPT_CODE = 'D2';