SELECT E.EMP_NAME, E.JOB_CODE, E.DEPT_CODE, E.HIRE_DATE
FROM EMPLOYEE E
         JOIN (
    SELECT DISTINCT DEPT_CODE, JOB_CODE
    FROM EMPLOYEE
    WHERE ENT_YN = 'Y'
      AND SUBSTRING(EMP_NO, 8, 1) IN ('2', '4')
) R
              ON E.DEPT_CODE = R.DEPT_CODE
                  AND E.JOB_CODE = R.JOB_CODE;
